### PR TITLE
Megapack

### PR DESCRIPTION
**Pull request by elia**
I'll propose all this stuff at once, **but I'm ready to split into different PRs** if you want just a subset.

- Add support for Rational/Complex Literal (Ruby 2.1), e.g. `23i` and `23r`
- Add Symbols (Intern) percent string support, e.g. `%i[some symbols]` and  `%I[some #{:symbols}]`
- Add <kbd>i⇥</kbd> to insert `inspect`
- Add @ expantion to memoized ivar (see below)
- Skip multiple extensions in the class name, e.g. the class name generated from a file named `my_class.js.rb` will be `MyClass` instead of `MyClass.js`

---

### Add @ expansion to memoized ivar

Will expand `@` to a memoized assignment of a variable with the same name as the including method.

#### General case

```ruby
def some_method
  @⇥
end
```
is expanded to:
```ruby
def some_method
  @some_method ||= some_method
end
```

#### With previous content

```ruby
def some_method
  @⇥previous_content
end
```
is expanded to:

```ruby
def some_method
  @some_method ||= previous_content
end
```

#### Inside `initialize`

```ruby
def initialize
  @⇥
end
```
is expanded to:

```ruby
def initialize
  @instance_variable = instance_variable
end
```

### CODE REVIEW

**Comment by mmzoo** [comment]
I find these changes very useful and would be happy if they could be merged. This pull request would also make #44 obsolete. Two for the price of one :)

**Comment by infininight** [comment]
Added as 535dd86bf8b8013cd4e60a846f66fac758686b17...0b5c0f398bc3c1b76a96bca3255f4645b25a413d, percent literals added in a different form in a6a17019df8899528485e5d500be2dbf94dafc61. Menu layout added to cbd530173521d0ee09d7ae30f34a1e20430a3a49 and f1f419732b39e1b48843a9249e4f56848ba91ae4. Thanks!

**Comment by mmzoo** [comment]
Oooh, it works! Sweet, thank you!

**Comment by elia** [comment]
Thanks @infininight!

**Pull request closed without merging**
