### PR TITLE
run_script: make test matching use pattern.

### PR DESCRIPTION
**Pull request by mikemcquaid**
In my experience the previous version was not always enough to match across various test systems that may have additional ways of generating the names for tests.

Let me know if this is the wrong approach and I'll try and work on another approach you suggest to fix my problems.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
@infininight Any thoughts on this? Thanks!

**Comment by sanssecours** [comment]
Hi Mike,

> @infininight @sanssecours @sorbits Any thoughts on this? Thanks!

I think I am the wrong person to ask here, since I am only a [minor contributor](https://github.com/textmate/ruby.tmbundle/commits/master?author=sanssecours). I usually test my Ruby code with [rubydoctests](https://github.com/tslocke/rubydoctest), which neither works with the current version of “Run Focused Unit Test” nor with the updates from your code.

Maybe it would help if you could provide some code examples (test systems) that work with your changes, but do not with the current code.

Kind regards,
  René

**Comment by infininight** [comment]
Need some feedback on this pull request from someone more familiar with the various testing methods in ruby. Further explanation into your exact issue with the current state as @sanssecours stated would be good as well.

**Comment by mikemcquaid** [comment]
It seems the project I was trying to fix with this customises too much MiniTest stuff for this to be a useful upstream contribution. Will try and play with that project rather than this. Thanks and sorry for the useless PR!

**Pull request closed without merging**
